var R=require("../chunks/ssr/[turbopack]_runtime.js")("server/app/page.js")
R.c("server/chunks/ssr/06cq_next_dist_esm_0wqxuca._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0cw0-~z._.js")
R.c("server/chunks/ssr/06cq_next_dist_esm_060biru._.js")
R.c("server/chunks/ssr/06cq_next_dist_compiled_0xco-.3._.js")
R.c("server/chunks/ssr/06cq_next_dist_server_route-modules_app-page_0shhht_._.js")
R.c("server/chunks/ssr/[externals]__0n13xf4._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0wr6gbv._.js")
R.c("server/chunks/ssr/06cq_next_dist_client_components_0mto~-4._.js")
R.c("server/chunks/ssr/06cq_next_dist_client_components_builtin_forbidden_0tu~y68.js")
R.c("server/chunks/ssr/06cq_next_dist_client_components_builtin_unauthorized_0t75gxc.js")
R.c("server/chunks/ssr/06cq_next_dist_client_components_builtin_global-error_06cpd7l.js")
R.c("server/chunks/ssr/Projects_Antigravity__next-internal_server_app_page_actions_0566svq.js")
R.m("[project]/Projects/Antigravity/node_modules/next/dist/esm/build/templates/app-page.js?page=/page { MODULE_0 => \"[project]/Projects/Antigravity/app/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_1 => \"[project]/Projects/Antigravity/node_modules/next/dist/client/components/builtin/not-found.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_2 => \"[project]/Projects/Antigravity/node_modules/next/dist/client/components/builtin/forbidden.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_3 => \"[project]/Projects/Antigravity/node_modules/next/dist/client/components/builtin/unauthorized.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_4 => \"[project]/Projects/Antigravity/node_modules/next/dist/client/components/builtin/global-error.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_5 => \"[project]/Projects/Antigravity/app/page.tsx [app-rsc] (ecmascript, Next.js Server Component)\" } [app-rsc] (ecmascript)")
module.exports=R.m("[project]/Projects/Antigravity/node_modules/next/dist/esm/build/templates/app-page.js?page=/page { MODULE_0 => \"[project]/Projects/Antigravity/app/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_1 => \"[project]/Projects/Antigravity/node_modules/next/dist/client/components/builtin/not-found.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_2 => \"[project]/Projects/Antigravity/node_modules/next/dist/client/components/builtin/forbidden.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_3 => \"[project]/Projects/Antigravity/node_modules/next/dist/client/components/builtin/unauthorized.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_4 => \"[project]/Projects/Antigravity/node_modules/next/dist/client/components/builtin/global-error.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_5 => \"[project]/Projects/Antigravity/app/page.tsx [app-rsc] (ecmascript, Next.js Server Component)\" } [app-rsc] (ecmascript)").exports
