// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/auth/error" | "/auth/login" | "/auth/sign-up" | "/auth/sign-up-success" | "/dashboard" | "/dashboard/chat" | "/dashboard/experience" | "/dashboard/leaderboard" | "/dashboard/modules" | "/dashboard/modules/[id]" | "/dashboard/progress" | "/dashboard/settings" | "/dashboard/skills" | "/onboarding"
type AppRouteHandlerRoutes = "/api/badges" | "/api/extract-skills" | "/api/flashcards" | "/api/learning-paths" | "/api/preferences" | "/api/profile" | "/api/skills" | "/api/skills/[id]" | "/api/skills/bulk" | "/api/work-experience" | "/api/work-experience/[id]" | "/auth/callback"
type PageRoutes = never
type LayoutRoutes = "/" | "/dashboard"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/badges": {}
  "/api/extract-skills": {}
  "/api/flashcards": {}
  "/api/learning-paths": {}
  "/api/preferences": {}
  "/api/profile": {}
  "/api/skills": {}
  "/api/skills/[id]": { "id": string; }
  "/api/skills/bulk": {}
  "/api/work-experience": {}
  "/api/work-experience/[id]": { "id": string; }
  "/auth/callback": {}
  "/auth/error": {}
  "/auth/login": {}
  "/auth/sign-up": {}
  "/auth/sign-up-success": {}
  "/dashboard": {}
  "/dashboard/chat": {}
  "/dashboard/experience": {}
  "/dashboard/leaderboard": {}
  "/dashboard/modules": {}
  "/dashboard/modules/[id]": { "id": string; }
  "/dashboard/progress": {}
  "/dashboard/settings": {}
  "/dashboard/skills": {}
  "/onboarding": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/dashboard": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
